// <auto-generated>
// This file is generated by Tools/CldrDataGenerator. Do not edit it manually.
// </auto-generated>

namespace Singulink.Globalization;

partial class CldrCurrencyData
{
    /// <summary>
    /// Gets the version of the Unicode Common Locale Data Repository (CLDR) that the currency data in this package was generated from.
    /// </summary>
    public const string CldrVersion = "48.0.0";
}
