// Generates the compact currency data file embedded in the Singulink.Globalization.Currency.Cldr package from the Unicode CLDR JSON distribution.
//
// Usage: dotnet run --project Tools/CldrDataGenerator -- [cldr-version]
//
// The tool downloads the cldr-core and cldr-numbers-full npm packages for the specified CLDR version (defaults to the version currently referenced by
// the Cldr package), extracts the currency data and writes:
//
//   Source/Singulink.Globalization.Currency.Cldr/Data/CurrencyData.bin   (gzip compressed binary data, see CldrDataFormat.cs for the layout)
//   Source/Singulink.Globalization.Currency.Cldr/CldrCurrencyData.Version.g.cs
//
// See https://github.com/unicode-org/cldr-json for the source data. CLDR data is licensed under the Unicode License (https://www.unicode.org/license.txt).

using System.Formats.Tar;
using System.IO.Compression;
using System.Text.Json;
using System.Text.RegularExpressions;
using Singulink.Globalization.Tools;

string repoRoot = FindRepoRoot();
string cldrProjectDir = Path.Combine(repoRoot, "Source", "Singulink.Globalization.Currency.Cldr");
string versionFilePath = Path.Combine(cldrProjectDir, "CldrCurrencyData.Version.g.cs");
string dataFilePath = Path.Combine(cldrProjectDir, "Data", "CurrencyData.bin");

string version = args.Length > 0 ? args[0] : ReadCurrentVersion(versionFilePath);
Console.WriteLine($"Generating CLDR currency data for CLDR version {version}...");

string workDir = Path.Combine(Path.GetTempPath(), "singulink-cldr", version);
Directory.CreateDirectory(workDir);

using var http = new HttpClient();

string coreDir = await DownloadAndExtractPackageAsync(http, "cldr-core", version, workDir);
string numbersDir = await DownloadAndExtractPackageAsync(http, "cldr-numbers-full", version, workDir);

var data = CldrCurrencyDataBuilder.Build(coreDir, numbersDir);

Directory.CreateDirectory(Path.GetDirectoryName(dataFilePath)!);
CldrDataFormat.Write(dataFilePath, version, data);
File.WriteAllText(versionFilePath, GenerateVersionFile(version));

Console.WriteLine($"Wrote {data.Currencies.Count} currencies and {data.Locales.Count} locales ({data.LocaleEntryCount} locale entries) to:");
Console.WriteLine($"  {dataFilePath} ({new FileInfo(dataFilePath).Length:N0} bytes)");
Console.WriteLine($"  {versionFilePath}");

static string FindRepoRoot()
{
    string? dir = AppContext.BaseDirectory;

    while (dir is not null)
    {
        if (File.Exists(Path.Combine(dir, "Singulink.Globalization.Currency.sln")))
            return dir;

        dir = Path.GetDirectoryName(dir);
    }

    throw new InvalidOperationException("Could not locate the repository root from the tool's base directory.");
}

static string ReadCurrentVersion(string versionFilePath)
{
    if (!File.Exists(versionFilePath))
        throw new InvalidOperationException($"No CLDR version specified and no existing version file found at '{versionFilePath}'.");

    var match = Regex.Match(File.ReadAllText(versionFilePath), @"CldrVersion\s*=\s*""([^""]+)""");

    if (!match.Success)
        throw new InvalidOperationException($"Could not read the current CLDR version from '{versionFilePath}'.");

    return match.Groups[1].Value;
}

static async Task<string> DownloadAndExtractPackageAsync(HttpClient http, string package, string version, string workDir)
{
    string extractDir = Path.Combine(workDir, package);

    if (Directory.Exists(Path.Combine(extractDir, "package")))
    {
        Console.WriteLine($"Using cached {package}@{version} from '{extractDir}'.");
        return Path.Combine(extractDir, "package");
    }

    string url = $"https://registry.npmjs.org/{package}/-/{package}-{version}.tgz";
    Console.WriteLine($"Downloading {url}...");

    using var response = await http.GetAsync(url);
    response.EnsureSuccessStatusCode();

    await using var tgzStream = await response.Content.ReadAsStreamAsync();
    await using var gzip = new GZipStream(tgzStream, CompressionMode.Decompress);

    Directory.CreateDirectory(extractDir);
    await TarFile.ExtractToDirectoryAsync(gzip, extractDir, overwriteFiles: true);

    return Path.Combine(extractDir, "package");
}

static string GenerateVersionFile(string version)
{
    return $$"""
        // <auto-generated>
        // This file is generated by Tools/CldrDataGenerator. Do not edit it manually.
        // </auto-generated>

        namespace Singulink.Globalization;

        partial class CldrCurrencyData
        {
            /// <summary>
            /// Gets the version of the Unicode Common Locale Data Repository (CLDR) that the currency data in this package was generated from.
            /// </summary>
            public const string CldrVersion = "{{version}}";
        }

        """.ReplaceLineEndings("\r\n");
}
